/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FiltroRenovacionesDialog.java
 *
 * Created on 16/09/2010, 03:38:46 PM
 */
package vista.reportes;

import controlador.personas.PersonaLookupControllerPorNombre;
import controlador.reportes.ReporteController;
import controlador.util.DefaultLookupController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import modelo.entidades.Reporte;
import modelo.entidades.polizas.dominio.GrupoPoliza;
import modelo.entidades.polizas.dominio.RamoPoliza;
import modelo.entidades.polizas.recibos.dominio.TipoZona;
import modelo.entidades.polizas.recibos.maestra.Recibo;
import modelo.utilitario.FiltroRenovacion;
import org.openswing.swing.form.client.FormController;
import org.openswing.swing.mdi.client.InternalFrame;
import org.openswing.swing.mdi.client.MDIFrame;
import org.openswing.swing.message.send.java.FilterWhereClause;
import org.openswing.swing.util.client.ClientUtils;

/**
 *
 * @author PAPA
 */
public class FiltroRenovacionesDialog extends InternalFrame {

    private Reporte reporte;
    private String estilo;
    private FiltroRenovacion renovacion;
    private EsperaDialog es;
    private Map filtros = new HashMap(0);
    private ReporteController controlador = new ReporteController();

    /** Creates new form FiltroRenovacionesDialog */
    public FiltroRenovacionesDialog(Reporte reporte, String estilo) {
        initComponents();

        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);

        jFormattedTextField1.setText(String.valueOf(Calendar.getInstance().get(Calendar.YEAR)));

        this.getRootPane().setDefaultButton(jButton1);
        this.reporte = reporte;
        this.estilo = estilo;

        PersonaLookupControllerPorNombre lookupCompania = new PersonaLookupControllerPorNombre("SEG");
        lookupCompania.addLookup2ParentLink("compania");
        lookupCompania.addLookup2ParentLink("nombreCorto", "compania.nombreCorto");
        codLookupControl2.setLookupController(lookupCompania);

        PersonaLookupControllerPorNombre lookupProductor = new PersonaLookupControllerPorNombre("PRD");
        lookupProductor.addLookup2ParentLink("productor");
        lookupProductor.addLookup2ParentLink("nombreCorto", "productor.nombreCorto");
        codLookupControl5.setLookupController(lookupProductor);

        PersonaLookupControllerPorNombre lookupCobrador = new PersonaLookupControllerPorNombre("COB");
        lookupCobrador.addLookup2ParentLink("cobrador");
        lookupCobrador.addLookup2ParentLink("nombreCorto", "cobrador.nombreCorto");
        codLookupControl6.setLookupController(lookupCobrador);

        DefaultLookupController grupo = new DefaultLookupController(GrupoPoliza.class.getName());
        grupo.addLookup2ParentLink("grupo");
        codLookupControl4.setLookupController(grupo);

        DefaultLookupController lookupGrupoPoliza = new DefaultLookupController(
                TipoZona.class.getName());
        lookupGrupoPoliza.addLookup2ParentLink("tipoZona");
        codLookupControl7.setLookupController(lookupGrupoPoliza);

        DefaultLookupController ramo = new DefaultLookupController(RamoPoliza.class.getName());
        ramo.addLookup2ParentLink("ramo");
        codLookupControl3.setLookupController(ramo);

        jButton1.addActionListener(new Filtro());
        MDIFrame.add(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        dateControl1 = new org.openswing.swing.client.DateControl();
        dateControl2 = new org.openswing.swing.client.DateControl();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        form1 = new org.openswing.swing.form.client.Form();
        labelControl7 = new org.openswing.swing.client.LabelControl();
        codLookupControl2 = new org.openswing.swing.client.CodLookupControl();
        codLookupControl3 = new org.openswing.swing.client.CodLookupControl();
        labelControl8 = new org.openswing.swing.client.LabelControl();
        labelControl9 = new org.openswing.swing.client.LabelControl();
        codLookupControl4 = new org.openswing.swing.client.CodLookupControl();
        labelControl10 = new org.openswing.swing.client.LabelControl();
        codLookupControl5 = new org.openswing.swing.client.CodLookupControl();
        labelControl11 = new org.openswing.swing.client.LabelControl();
        codLookupControl6 = new org.openswing.swing.client.CodLookupControl();
        labelControl12 = new org.openswing.swing.client.LabelControl();
        codLookupControl7 = new org.openswing.swing.client.CodLookupControl();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtro");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecciones el Mes y Año"));

        jLabel1.setText("Mes de Renovaciones:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel4.setText("Año:");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, 0, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mes", jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el rango de fechas"));

        jLabel2.setText("Desde:");

        jLabel3.setText("Hasta:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateControl1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dateControl2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateControl1, dateControl2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateControl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateControl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rango de Fechas", jPanel2);

        jButton1.setText("Filtrar");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros de Filtrado"));

        form1.setVOClassName(FiltroRenovacion.class.getName());

        labelControl7.setLabel("compania");

        codLookupControl2.setAttributeName("compania.nombreLargo");
        codLookupControl2.setMaxCharacters(10);

        codLookupControl3.setAttributeName("ramo.nombre");
        codLookupControl3.setMaxCharacters(10);

        labelControl8.setLabel("ramo");

        labelControl9.setLabel("grupo");

        codLookupControl4.setAttributeName("grupo.nombre");
        codLookupControl4.setMaxCharacters(10);

        labelControl10.setLabel("productor");

        codLookupControl5.setAttributeName("productor.nombreLargo");
        codLookupControl5.setMaxCharacters(10);

        labelControl11.setLabel("cobrador");

        codLookupControl6.setAttributeName("cobrador.nombreLargo");
        codLookupControl6.setMaxCharacters(10);

        labelControl12.setLabel("zona");

        codLookupControl7.setAttributeName("tipoZona.nombre");
        codLookupControl7.setMaxCharacters(10);

        jRadioButton1.setText("Dia-Mes");

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Dia-mes-Año");

        javax.swing.GroupLayout form1Layout = new javax.swing.GroupLayout(form1);
        form1.setLayout(form1Layout);
        form1Layout.setHorizontalGroup(
            form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(labelControl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(labelControl8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl3, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(labelControl9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl4, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(labelControl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl5, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form1Layout.createSequentialGroup()
                        .addComponent(labelControl11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl6, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(labelControl12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl7, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)))
                .addContainerGap())
        );

        form1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelControl10, labelControl11, labelControl12, labelControl7, labelControl8, labelControl9});

        form1Layout.setVerticalGroup(
            form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        form1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {codLookupControl2, labelControl10, labelControl11, labelControl12, labelControl7, labelControl8, labelControl9});

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(form1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(form1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private org.openswing.swing.client.CodLookupControl codLookupControl2;
    private org.openswing.swing.client.CodLookupControl codLookupControl3;
    private org.openswing.swing.client.CodLookupControl codLookupControl4;
    private org.openswing.swing.client.CodLookupControl codLookupControl5;
    private org.openswing.swing.client.CodLookupControl codLookupControl6;
    private org.openswing.swing.client.CodLookupControl codLookupControl7;
    private org.openswing.swing.client.DateControl dateControl1;
    private org.openswing.swing.client.DateControl dateControl2;
    private org.openswing.swing.form.client.Form form1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.openswing.swing.client.LabelControl labelControl10;
    private org.openswing.swing.client.LabelControl labelControl11;
    private org.openswing.swing.client.LabelControl labelControl12;
    private org.openswing.swing.client.LabelControl labelControl7;
    private org.openswing.swing.client.LabelControl labelControl8;
    private org.openswing.swing.client.LabelControl labelControl9;
    // End of variables declaration//GEN-END:variables

    class Filtro extends FormController implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            renovacion = ((FiltroRenovacion) FiltroRenovacionesDialog.this.form1.getVOModel().getValueObject());
//            ReporteController controlador = new ReporteController();
//            Map filtros = new HashMap(0);
            FilterWhereClause parametros[] = new FilterWhereClause[2];
            Calendar c = Calendar.getInstance();

            boolean vacio = true;

            if (jRadioButton2.isSelected()) {
                if (renovacion.getCobrador() != null && renovacion.getCobrador().getId() != null) {
                    FilterWhereClause cob[] = new FilterWhereClause[2];
                    cob[0] = new FilterWhereClause("cobrador2.id", "=", renovacion.getCobrador().getId());
                    filtros.put("cobrador2.id", cob);
                    vacio = false;
                }
                if (renovacion.getCompania() != null && renovacion.getCompania().getId() != null) {
                    FilterWhereClause com[] = new FilterWhereClause[2];
                    com[0] = new FilterWhereClause("poliza.compania.id", "=", renovacion.getCompania().getId());
                    filtros.put("poliza.compania.id", com);
                    vacio = false;
                }

                if (renovacion.getGrupo() != null && renovacion.getGrupo().getId() != null) {
                    FilterWhereClause gru[] = new FilterWhereClause[2];
                    gru[0] = new FilterWhereClause("poliza.grupoPoliza.id", "=", renovacion.getGrupo().getId());
                    filtros.put("poliza.grupoPoliza.id", gru);
                    vacio = false;
                }

                if (renovacion.getProductor() != null && renovacion.getProductor().getId() != null) {
                    FilterWhereClause pro[] = new FilterWhereClause[2];
                    pro[0] = new FilterWhereClause("poliza.productor.id", "=", renovacion.getProductor().getId());
                    filtros.put("poliza.productor.id", pro);
                    vacio = false;
                }

                if (renovacion.getRamo() != null && renovacion.getRamo().getId() != null) {
                    FilterWhereClause ram[] = new FilterWhereClause[2];
                    ram[0] = new FilterWhereClause("poliza.ramoPoliza.id", "=", renovacion.getRamo().getId());
                    filtros.put("poliza.ramoPoliza.id", ram);
                    vacio = false;
                }

                if (renovacion.getTipoZona() != null && renovacion.getTipoZona().getId() != null) {
                    FilterWhereClause zon[] = new FilterWhereClause[2];
                    zon[0] = new FilterWhereClause("zona.id", "=", renovacion.getTipoZona().getId());
                    filtros.put("zona.id", zon);
                    vacio = false;
                }


                switch (jTabbedPane1.getSelectedIndex()) {
                    case 0:
                        if (jFormattedTextField1.getText().compareTo("") == 0 || jFormattedTextField1.getText() == null) {
                            JOptionPane.showMessageDialog(MDIFrame.getInstance(), "Debe escribir un año.");
                            return;
                        }
                        Calendar desde2 = Calendar.getInstance();
                        desde2.set(Calendar.MONTH, jComboBox1.getSelectedIndex());
                        desde2.set(Calendar.DATE, 1);
                        desde2.set(Calendar.YEAR, Integer.valueOf(jFormattedTextField1.getText()));

                        Calendar hasta2 = Calendar.getInstance();
                        hasta2.set(Calendar.MONTH, jComboBox1.getSelectedIndex() + 1);
                        hasta2.set(Calendar.DATE, 1);
                        hasta2.set(Calendar.YEAR, Integer.valueOf(jFormattedTextField1.getText()));

                        //validacion si pasa de año
                        if (hasta2.get(Calendar.MONTH) == 12) {
                            hasta2.set(Calendar.MONTH, 1);
                            hasta2.set(Calendar.YEAR, hasta2.get(Calendar.YEAR) + 1);
                        }

                        parametros[0] = new FilterWhereClause("vigenciaHasta", ">=", desde2.getTime());
                        parametros[1] = new FilterWhereClause("vigenciaHasta", "<", hasta2.getTime());
                        vacio = false;
                        break;
                    case 1:
                        if (dateControl1.getDate() != null && dateControl2.getDate() != null) {
                            parametros[0] = new FilterWhereClause("vigenciaHasta", ">=", dateControl1.getDate());
                            parametros[1] = new FilterWhereClause("vigenciaHasta", "<=", dateControl2.getDate());
                            filtros.put("vigenciaHasta", parametros);
                            vacio = false;
                        } else if (dateControl1.getDate() != null) {
                            JOptionPane.showMessageDialog(MDIFrame.getInstance(), "Falta Ingresar la fecha Hasta en el Rango de Fechas.\n Para los campos Fecha de Vigencia (Hasta)");
                            return;
                        } else if (dateControl2.getDate() != null) {
                            JOptionPane.showMessageDialog(MDIFrame.getInstance(), "Falta Ingresar la fecha Desde en el Rango de Fechas.\n Para los campos Fecha de Vigencia (Hasta)");
                            return;
                        }
                        break;
                }
                filtros.put("vigenciaHasta", parametros);

                if (vacio) {
                    switch (JOptionPane.showConfirmDialog(MDIFrame.getInstance(), "NO ha colocado ningun parametro.\n ¿Desea realizar un Reporte de las Renovaciones de este Mes?")) {
                        case JOptionPane.YES_OPTION:
                            Calendar desde2 = Calendar.getInstance();
                            desde2.set(Calendar.DATE, 1);

                            Calendar hasta2 = Calendar.getInstance();
                            hasta2.set(Calendar.MONTH, desde2.get(Calendar.MONTH) + 1);
                            hasta2.set(Calendar.DATE, 1);

                            FilterWhereClause parametros2[] = new FilterWhereClause[2];
                            parametros2[0] = new FilterWhereClause("vigenciaHasta", ">=", desde2.getTime());
                            parametros2[1] = new FilterWhereClause("vigenciaHasta", "<", hasta2.getTime());
                            filtros.put("vigenciaHasta", parametros);

                            mostrarReporte();
                            break;
                    }
                } else {
                    mostrarReporte();
                }
            }else
            {
                
            }
        }

        private void mostrarReporte() {
            es = new EsperaDialog(null, false);
            ClientUtils.centerDialog(MDIFrame.getInstance(), es);
            new Thread() {

                @Override
                public void run() {
                    es.setVisible(true);
                    controlador.loadData(reporte, estilo, 1, 0, filtros, new ArrayList(0), new ArrayList(0), Recibo.class, new HashMap(0));
                    es.dispose();
                }
            }.start();
            es.dispose();
        }
    }
}
