/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FiltroRenovacionesDialog.java
 *
 * Created on 16/09/2010, 03:38:46 PM
 */

package vista.reportes;

import controlador.personas.PersonaLookupControllerPorNombre;
import controlador.reportes.ReporteController;
import controlador.util.DefaultLookupController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import modelo.entidades.Reporte;
import modelo.entidades.polizas.dominio.GrupoPoliza;
import modelo.entidades.polizas.dominio.RamoPoliza;
import modelo.entidades.polizas.recibos.dominio.TipoDistribucion;
import modelo.entidades.polizas.recibos.dominio.TipoZona;
import modelo.entidades.polizas.recibos.maestra.Distribucion;
import modelo.utilitario.FiltroDistribucion;
import org.openswing.swing.form.client.FormController;
import org.openswing.swing.mdi.client.InternalFrame;
import org.openswing.swing.mdi.client.MDIFrame;
import org.openswing.swing.message.send.java.FilterWhereClause;
import org.openswing.swing.util.client.ClientUtils;

/**
 *
 * @author PAPA
 */
public class FiltroDistribucionDialog extends InternalFrame {

    private Reporte reporte;
    private String estilo;
    private FiltroDistribucion distribucion;
    private EsperaDialog es;
    private ReporteController controlador;
    private Map filtros = new HashMap(0);

    /** Creates new form FiltroRenovacionesDialog */
    public FiltroDistribucionDialog(Reporte reporte, String estilo) {
        initComponents();

        //jFormattedTextField1.setText(String.valueOf(Calendar.getInstance().get(Calendar.YEAR)));

        this.getRootPane().setDefaultButton(jButton1);
        this.reporte = reporte;
        this.estilo = estilo;

        PersonaLookupControllerPorNombre lookupCompania = new PersonaLookupControllerPorNombre("SEG");
        lookupCompania.addLookup2ParentLink("compania");
        lookupCompania.addLookup2ParentLink("nombreCorto", "compania.nombreCorto");
        codLookupControl2.setLookupController(lookupCompania);

        PersonaLookupControllerPorNombre lookupProductor = new PersonaLookupControllerPorNombre("PRD");
        lookupProductor.addLookup2ParentLink("productor");
        lookupProductor.addLookup2ParentLink("nombreCorto", "productor.nombreCorto");
        codLookupControl5.setLookupController(lookupProductor);

        PersonaLookupControllerPorNombre lookupCobrador = new PersonaLookupControllerPorNombre("COB");
        lookupCobrador.addLookup2ParentLink("cobrador");
        lookupCobrador.addLookup2ParentLink("nombreCorto", "cobrador.nombreCorto");
        codLookupControl6.setLookupController(lookupCobrador);

        DefaultLookupController grupo = new DefaultLookupController(GrupoPoliza.class.getName());
        grupo.addLookup2ParentLink("grupo");
        codLookupControl4.setLookupController(grupo);

        DefaultLookupController tipoDistribucionNombre = new DefaultLookupController(TipoDistribucion.class.getName());
        tipoDistribucionNombre.addLookup2ParentLink("tipoDistribucion");
        codLookupControl8.setLookupController(tipoDistribucionNombre);

        DefaultLookupController lookupGrupoPoliza = new DefaultLookupController(TipoZona.class.getName());
        lookupGrupoPoliza.addLookup2ParentLink("tipoZona");
        codLookupControl7.setLookupController(lookupGrupoPoliza);

        DefaultLookupController ramo = new DefaultLookupController(RamoPoliza.class.getName());
        ramo.addLookup2ParentLink("ramo");
        codLookupControl3.setLookupController(ramo);

        jButton1.addActionListener(new FiltroDistribuciones());

        MDIFrame.add(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dateControl1 = new org.openswing.swing.client.DateControl();
        dateControl2 = new org.openswing.swing.client.DateControl();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dateControl3 = new org.openswing.swing.client.DateControl();
        dateControl4 = new org.openswing.swing.client.DateControl();
        dateControl5 = new org.openswing.swing.client.DateControl();
        dateControl6 = new org.openswing.swing.client.DateControl();
        dateControl7 = new org.openswing.swing.client.DateControl();
        dateControl8 = new org.openswing.swing.client.DateControl();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        form1 = new org.openswing.swing.form.client.Form();
        labelControl7 = new org.openswing.swing.client.LabelControl();
        codLookupControl2 = new org.openswing.swing.client.CodLookupControl();
        codLookupControl3 = new org.openswing.swing.client.CodLookupControl();
        labelControl8 = new org.openswing.swing.client.LabelControl();
        labelControl9 = new org.openswing.swing.client.LabelControl();
        codLookupControl4 = new org.openswing.swing.client.CodLookupControl();
        labelControl10 = new org.openswing.swing.client.LabelControl();
        codLookupControl5 = new org.openswing.swing.client.CodLookupControl();
        labelControl11 = new org.openswing.swing.client.LabelControl();
        codLookupControl6 = new org.openswing.swing.client.CodLookupControl();
        labelControl12 = new org.openswing.swing.client.LabelControl();
        codLookupControl7 = new org.openswing.swing.client.CodLookupControl();
        codLookupControl8 = new org.openswing.swing.client.CodLookupControl();
        labelControl13 = new org.openswing.swing.client.LabelControl();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtro de Distribución de Comisión");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecciones el Mes y Año"));

        jLabel1.setText("Mes de Cobro:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel4.setText("Año:");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel5.setText("Mes de Pago de Comision:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel6.setText("Año:");

        jLabel7.setText("Mes de Vigencia (Desde):");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jLabel8.setText("Año:");

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel9.setText("Mes de Vigencia (Hasta):");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });

        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel10.setText("Año:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox4, 0, 103, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, 0, 0, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox3, 0, 103, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel5, jLabel7, jLabel9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox4, jLabel1, jLabel5, jLabel7, jLabel9});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mes", jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el rango de fechas"));

        jLabel2.setText("Desde:");

        jLabel3.setText("Hasta:");

        jLabel11.setText("Fecha de Cobro:");

        jLabel12.setText("Fecha de Pago de Comision:");

        jLabel13.setText("Fecha de Vigencia (Desde):");

        jLabel14.setText("Fecha de Vigencia (Hasta):");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(dateControl1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dateControl7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateControl5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateControl3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dateControl8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(dateControl6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(dateControl4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(dateControl2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateControl1, dateControl2, dateControl3, dateControl4, dateControl5, dateControl6, dateControl7, dateControl8});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateControl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateControl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateControl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateControl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateControl6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateControl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateControl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateControl8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateControl7, jLabel11, jLabel12, jLabel13, jLabel14});

        jTabbedPane1.addTab("Rango de Fechas", jPanel2);

        jButton1.setText("Filtrar");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros de Filtrado"));

        form1.setVOClassName(FiltroDistribucion.class.getName());

        labelControl7.setLabel("compania");

        codLookupControl2.setAttributeName("compania.nombreLargo");
        codLookupControl2.setMaxCharacters(10);

        codLookupControl3.setAttributeName("ramo.nombre");
        codLookupControl3.setMaxCharacters(10);

        labelControl8.setLabel("ramo");

        labelControl9.setLabel("grupo");

        codLookupControl4.setAttributeName("grupo.nombre");
        codLookupControl4.setMaxCharacters(10);

        labelControl10.setLabel("productor");

        codLookupControl5.setAttributeName("productor.nombreLargo");
        codLookupControl5.setMaxCharacters(10);

        labelControl11.setLabel("recibo.cobrador");
        labelControl11.setToolTipText("Cobrador que Aparece en el recibo");

        codLookupControl6.setAttributeName("cobrador.nombreLargo");
        codLookupControl6.setMaxCharacters(10);

        labelControl12.setLabel("zona");

        codLookupControl7.setAttributeName("tipoZona.nombre");
        codLookupControl7.setMaxCharacters(10);

        codLookupControl8.setAttributeName("tipoDistribucion.nombre");
        codLookupControl8.setMaxCharacters(10);

        labelControl13.setLabel("tipoDistribucion");

        javax.swing.GroupLayout form1Layout = new javax.swing.GroupLayout(form1);
        form1.setLayout(form1Layout);
        form1Layout.setHorizontalGroup(
            form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(labelControl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(labelControl8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl3, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(labelControl9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl4, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(labelControl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl5, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form1Layout.createSequentialGroup()
                        .addComponent(labelControl11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl6, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(labelControl13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl8, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                    .addGroup(form1Layout.createSequentialGroup()
                        .addComponent(labelControl12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codLookupControl7, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)))
                .addContainerGap())
        );

        form1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelControl10, labelControl11, labelControl12, labelControl13, labelControl7, labelControl8, labelControl9});

        form1Layout.setVerticalGroup(
            form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codLookupControl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelControl13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codLookupControl8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        form1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {codLookupControl2, labelControl10, labelControl11, labelControl12, labelControl7, labelControl8, labelControl9});

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(form1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(form1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        if (jComboBox4.getSelectedIndex() == 0) {
            jFormattedTextField4.setText("");
        }
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (jComboBox1.getSelectedIndex() == 0) {
            jFormattedTextField1.setText("");
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        if (jComboBox2.getSelectedIndex() == 0) {
            jFormattedTextField2.setText("");
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        if (jComboBox3.getSelectedIndex() == 0) {
            jFormattedTextField3.setText("");
        }
    }//GEN-LAST:event_jComboBox3ItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.client.CodLookupControl codLookupControl2;
    private org.openswing.swing.client.CodLookupControl codLookupControl3;
    private org.openswing.swing.client.CodLookupControl codLookupControl4;
    private org.openswing.swing.client.CodLookupControl codLookupControl5;
    private org.openswing.swing.client.CodLookupControl codLookupControl6;
    private org.openswing.swing.client.CodLookupControl codLookupControl7;
    private org.openswing.swing.client.CodLookupControl codLookupControl8;
    private org.openswing.swing.client.DateControl dateControl1;
    private org.openswing.swing.client.DateControl dateControl2;
    private org.openswing.swing.client.DateControl dateControl3;
    private org.openswing.swing.client.DateControl dateControl4;
    private org.openswing.swing.client.DateControl dateControl5;
    private org.openswing.swing.client.DateControl dateControl6;
    private org.openswing.swing.client.DateControl dateControl7;
    private org.openswing.swing.client.DateControl dateControl8;
    private org.openswing.swing.form.client.Form form1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.openswing.swing.client.LabelControl labelControl10;
    private org.openswing.swing.client.LabelControl labelControl11;
    private org.openswing.swing.client.LabelControl labelControl12;
    private org.openswing.swing.client.LabelControl labelControl13;
    private org.openswing.swing.client.LabelControl labelControl7;
    private org.openswing.swing.client.LabelControl labelControl8;
    private org.openswing.swing.client.LabelControl labelControl9;
    // End of variables declaration//GEN-END:variables

    class FiltroDistribuciones extends FormController implements ActionListener {

        public void actionPerformed(ActionEvent e) {

            distribucion = ((FiltroDistribucion) FiltroDistribucionDialog.this.form1.getVOModel().getValueObject());
            controlador = new ReporteController();
            boolean mascara[] = {false, false, false, false};

            boolean vacio = true;
            Calendar c = Calendar.getInstance();

            Date desde, hasta;

            if (distribucion.getCobrador() != null && distribucion.getCobrador().getId() != null) {
                FilterWhereClause cob[] = new FilterWhereClause[2];
                cob[0] = new FilterWhereClause("recibo.cobrador2.id", "=", distribucion.getCobrador().getId());
                vacio = false;
                filtros.put("recibo.cobrador2.id", cob);
            }
            if (distribucion.getCompania() != null && distribucion.getCompania().getId() != null) {
                FilterWhereClause com[] = new FilterWhereClause[2];
                com[0] = new FilterWhereClause("recibo.poliza.compania.id", "=", distribucion.getCompania().getId());
                vacio = false;
                filtros.put("recibo.poliza.compania.id", com);
            }

            if (distribucion.getGrupo() != null && distribucion.getGrupo().getId() != null) {
                FilterWhereClause gru[] = new FilterWhereClause[2];
                gru[0] = new FilterWhereClause("recibo.poliza.grupoPoliza.id", "=", distribucion.getGrupo().getId());
                vacio = false;
                filtros.put("recibo.poliza.grupoPoliza.id", gru);
            }

            if (distribucion.getProductor() != null && distribucion.getProductor().getId() != null) {
                FilterWhereClause pro[] = new FilterWhereClause[2];
                pro[0] = new FilterWhereClause("recibo.poliza.productor.id", "=", distribucion.getProductor().getId());
                vacio = false;
                filtros.put("recibo.poliza.productor.id", pro);
            }

            if (distribucion.getRamo() != null && distribucion.getRamo().getId() != null) {
                FilterWhereClause ram[] = new FilterWhereClause[2];
                ram[0] = new FilterWhereClause("recibo.poliza.ramoPoliza.id", "=", distribucion.getRamo().getId());
                vacio = false;
                filtros.put("recibo.poliza.ramoPoliza.id", ram);
            }

            if (distribucion.getTipoDistribucion() != null && distribucion.getTipoDistribucion().getId() != null) {
                FilterWhereClause distri[] = new FilterWhereClause[2];
                distri[0] = new FilterWhereClause("recibo.tipoDistribucionNombre", "=", distribucion.getTipoDistribucion().getNombre());
                vacio = false;
                filtros.put("recibo.tipoDistribucionNombre", distri);
            }

            if (distribucion.getTipoZona() != null && distribucion.getTipoZona().getId() != null) {
                FilterWhereClause zon[] = new FilterWhereClause[2];
                zon[0] = new FilterWhereClause("recibo.zona.id", "=", distribucion.getTipoZona().getId());
                vacio = false;
                filtros.put("recibo.zona.id", zon);
            }

            switch (jTabbedPane1.getSelectedIndex()) {
                case 0:
                    if (jComboBox1.getSelectedIndex() > 0) {
                        vacio = false;

                        FilterWhereClause parametros[] = new FilterWhereClause[2];

                        Calendar desde2 = Calendar.getInstance();
                        desde2.set(Calendar.MONTH, jComboBox1.getSelectedIndex() - 1);
                        desde2.set(Calendar.DATE, 1);
                        desde2.set(Calendar.YEAR, Integer.valueOf(jFormattedTextField1.getText()));

                        Calendar hasta2 = Calendar.getInstance();
                        hasta2.set(Calendar.MONTH, jComboBox1.getSelectedIndex());
                        hasta2.set(Calendar.DATE, 1);
                        hasta2.set(Calendar.YEAR, Integer.valueOf(jFormattedTextField1.getText()));

                        //validacion si pasa de año
                        if (hasta2.get(Calendar.MONTH) == 12) {
                            hasta2.set(Calendar.MONTH, 1);
                            hasta2.set(Calendar.YEAR, hasta2.get(Calendar.YEAR) + 1);
                        }

                        System.out.println(hasta2.getTime());

                        parametros[0] = new FilterWhereClause("recibo.fechaCobro", ">=", desde2.getTime());
                        parametros[1] = new FilterWhereClause("recibo.fechaCobro", "<", hasta2.getTime());
                        filtros.put("recibo.fechaCobro", parametros);
                    }
                    if (jComboBox2.getSelectedIndex() > 0) {
                        vacio = false;

                        FilterWhereClause parametros[] = new FilterWhereClause[2];

                        Calendar desde2 = Calendar.getInstance();
                        desde2.set(Calendar.MONTH, jComboBox2.getSelectedIndex() - 1);
                        desde2.set(Calendar.DATE, 1);
                        desde2.set(Calendar.YEAR, Integer.valueOf(jFormattedTextField1.getText()));

                        Calendar hasta2 = Calendar.getInstance();
                        hasta2.set(Calendar.MONTH, jComboBox2.getSelectedIndex());
                        hasta2.set(Calendar.DATE, 1);
                        hasta2.set(Calendar.YEAR, Integer.valueOf(jFormattedTextField1.getText()));

                        //validacion si pasa de año
                        if (hasta2.get(Calendar.MONTH) == 12) {
                            hasta2.set(Calendar.MONTH, 1);
                            hasta2.set(Calendar.YEAR, hasta2.get(Calendar.YEAR) + 1);
                        }

                        parametros[0] = new FilterWhereClause("recibo.fechaPagoComision", ">=", desde2.getTime());
                        parametros[1] = new FilterWhereClause("recibo.fechaPagoComision", "<", hasta2.getTime());
                        filtros.put("recibo.fechaPagoComision", parametros);
                    }
                    if (jComboBox3.getSelectedIndex() > 0) {
                        vacio = false;

                        FilterWhereClause parametros[] = new FilterWhereClause[2];

                        Calendar desde2 = Calendar.getInstance();
                        desde2.set(Calendar.MONTH, jComboBox3.getSelectedIndex() - 1);
                        desde2.set(Calendar.DATE, 1);
                        desde2.set(Calendar.YEAR, Integer.valueOf(jFormattedTextField1.getText()));

                        Calendar hasta2 = Calendar.getInstance();
                        hasta2.set(Calendar.MONTH, jComboBox3.getSelectedIndex());
                        hasta2.set(Calendar.DATE, 1);
                        hasta2.set(Calendar.YEAR, Integer.valueOf(jFormattedTextField1.getText()));

                        //validacion si pasa de año
                        if (hasta2.get(Calendar.MONTH) == 12) {
                            hasta2.set(Calendar.MONTH, 1);
                            hasta2.set(Calendar.YEAR, hasta2.get(Calendar.YEAR) + 1);
                        }

                        parametros[0] = new FilterWhereClause("recibo.vigenciaDesde", ">=", desde2.getTime());
                        parametros[1] = new FilterWhereClause("recibo.vigenciaDesde", "<", hasta2.getTime());
                        filtros.put("recibo.vigenciaDesde", parametros);
                    }
                    if (jComboBox4.getSelectedIndex() > 0) {
                        vacio = false;

                        FilterWhereClause parametros[] = new FilterWhereClause[2];

                        Calendar desde2 = Calendar.getInstance();
                        desde2.set(Calendar.MONTH, jComboBox4.getSelectedIndex() - 1);
                        desde2.set(Calendar.DATE, 1);
                        desde2.set(Calendar.YEAR, Integer.valueOf(jFormattedTextField1.getText()));

                        Calendar hasta2 = Calendar.getInstance();
                        hasta2.set(Calendar.MONTH, jComboBox4.getSelectedIndex());
                        hasta2.set(Calendar.DATE, 1);
                        hasta2.set(Calendar.YEAR, Integer.valueOf(jFormattedTextField1.getText()));

                        //validacion si pasa de año
                        if (hasta2.get(Calendar.MONTH) == 12) {
                            hasta2.set(Calendar.MONTH, 1);
                            hasta2.set(Calendar.YEAR, hasta2.get(Calendar.YEAR) + 1);
                        }

                        parametros[0] = new FilterWhereClause("recibo.vigenciaHasta", ">=", desde2.getTime());
                        parametros[1] = new FilterWhereClause("recibo.vigenciaHasta", "<", hasta2.getTime());
                        filtros.put("recibo.vigenciaHasta", parametros);
                    }
                    break;
                case 1:
                    if (dateControl1.getDate() != null && dateControl2.getDate() != null) {
                        FilterWhereClause parametros[] = new FilterWhereClause[2];
                        parametros[0] = new FilterWhereClause("recibo.fechaCobro", ">=", dateControl1.getDate());
                        parametros[1] = new FilterWhereClause("recibo.fechaCobro", "<=", dateControl2.getDate());
                        filtros.put("recibo.fechaCobro", parametros);
                        vacio = false;
                    } else if (dateControl1.getDate() != null) {
                        JOptionPane.showMessageDialog(MDIFrame.getInstance(), "Falta Ingresar la fecha Hasta en el Rango de Fechas.\n Para los campos Fecha de Cobro");
                        return;
                    } else if (dateControl2.getDate() != null) {
                        JOptionPane.showMessageDialog(MDIFrame.getInstance(), "Falta Ingresar la fecha Desde en el Rango de Fechas.\n Para los campos Fecha de Cobro");
                        return;
                    }
                    if (dateControl3.getDate() != null && dateControl4.getDate() != null) {
                        FilterWhereClause parametros[] = new FilterWhereClause[2];
                        parametros[0] = new FilterWhereClause("recibo.fechaPagoComision", ">=", dateControl3.getDate());
                        parametros[1] = new FilterWhereClause("recibo.fechaPagoComision", "<=", dateControl4.getDate());
                        filtros.put("recibo.fechaPagoComision", parametros);
                        vacio = false;
                    } else if (dateControl3.getDate() != null) {
                        JOptionPane.showMessageDialog(MDIFrame.getInstance(), "Falta Ingresar la fecha Hasta en el Rango de Fechas.\n Para los campos Fecha de Pago de Comision");
                        return;
                    } else if (dateControl4.getDate() != null) {
                        JOptionPane.showMessageDialog(MDIFrame.getInstance(), "Falta Ingresar la fecha Desde en el Rango de Fechas.\n Para los campos Fecha de Pago de Comision");
                        return;
                    }
                    if (dateControl5.getDate() != null && dateControl6.getDate() != null) {
                        FilterWhereClause parametros[] = new FilterWhereClause[2];
                        parametros[0] = new FilterWhereClause("recibo.vigenciaDesde", ">=", dateControl5.getDate());
                        parametros[1] = new FilterWhereClause("recibo.vigenciaDesde", "<=", dateControl6.getDate());
                        filtros.put("recibo.vigenciaDesde", parametros);
                        vacio = false;
                    } else if (dateControl5.getDate() != null) {
                        JOptionPane.showMessageDialog(MDIFrame.getInstance(), "Falta Ingresar la fecha Hasta en el Rango de Fechas.\n Para los campos Fecha de Vigencia (Desde)");
                        return;
                    } else if (dateControl6.getDate() != null) {
                        JOptionPane.showMessageDialog(MDIFrame.getInstance(), "Falta Ingresar la fecha Desde en el Rango de Fechas.\n Para los campos Fecha de Vigencia (Desde)");
                        return;
                    }
                    if (dateControl7.getDate() != null && dateControl8.getDate() != null) {
                        FilterWhereClause parametros[] = new FilterWhereClause[2];
                        parametros[0] = new FilterWhereClause("recibo.vigenciaHasta", ">=", dateControl7.getDate());
                        parametros[1] = new FilterWhereClause("recibo.vigenciaHasta", "<=", dateControl8.getDate());
                        filtros.put("recibo.vigenciaHasta", parametros);
                        vacio = false;
                    } else if (dateControl7.getDate() != null) {
                        JOptionPane.showMessageDialog(MDIFrame.getInstance(), "Falta Ingresar la fecha Hasta en el Rango de Fechas.\n Para los campos Fecha de Vigencia (Hasta)");
                        return;
                    } else if (dateControl8.getDate() != null) {
                        JOptionPane.showMessageDialog(MDIFrame.getInstance(), "Falta Ingresar la fecha Desde en el Rango de Fechas.\n Para los campos Fecha de Vigencia (Hasta)");
                        return;
                    }
                    break;
            }

            if (vacio) {
                switch (JOptionPane.showConfirmDialog(MDIFrame.getInstance(), "NO ha colocado ningun parametro.\n ¿Desea realizar un Reporte de todos los recibos cargados?")) {
                    case JOptionPane.YES_OPTION:
                        mostrarReporte();
                        break;
                    case JOptionPane.NO_OPTION:
                        break;
                    case JOptionPane.CANCEL_OPTION:

                        break;
                }
            } else {
                mostrarReporte();
            }
        }

        private void mostrarReporte() {
            es = new EsperaDialog(null, false);
            ClientUtils.centerDialog(MDIFrame.getInstance(), es);
            new Thread() {

                @Override
                public void run() {
                    es.setVisible(true);
                    controlador.loadData(reporte, estilo, 1, 0, filtros, new ArrayList(0), new ArrayList(0), Distribucion.class, new HashMap(0));
                    es.dispose();
                }
            }.start();
            es.dispose();
        }
    }
}
